site_name: ONE Campaign Docs
copyright: Copyright ONE Campaign 2025
theme:
  favicon: assets/one_logo.png
  font:
    text: Calibri, sans-serif
  palette:
    # Palette toggle for light mode

    - scheme: default
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  name: material
  custom_dir: overrides
  logo: assets/one_logo_white.png
  features:
    - navigation.footer
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
#    - navigation.tabs.sticky
    - navigation.sections
#    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.top
    - search.suggest
nav:
  - Home: index.md
  - Python tools:
      - python_tools/index.md
      - bblocks:
        - python_tools/bblocks/index.md
        - Why bblocks?: python_tools/bblocks/why_bblocks.md
        - Getting Started: python_tools/bblocks/getting_started.md
        - bblocks-data-importers:
            - Overview: python_tools/bblocks/bblocks_data_importers.md
      - oda-reader:
        - python_tools/oda_reader/index.md
  - Methodologies:
      - Climate Finance: methodologies/climate_finance.md
      - Health Financing: methodologies/oda_reader.md
  - ETL:
      - ETL Overview: etl/index.md
  - Guidelines:
      - guidelines/index.md
      - Coding Principles: guidelines/coding.md
      - Data Analysis and Research principles: guidelines/data_analysis.md
      - Data Visualization Guideline:
          - guidelines/viz/index.md

plugins:
  - search
  - tags

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
